// src/components/BalanceDisplay.svelte
<script lang="ts">
import { Tooltip, TooltipContent, TooltipTrigger } from "@components/ui";
import { formatDkk, usdToDkk } from "@config/pricing";
import { t } from "@lib/i18n";

interface BalanceDisplayProps {
  /** Balance in USD (null when loading/error) */
  balanceUsd: number | null;
  /** Whether balance is currently being fetched */
  isLoading: boolean;
}

let { balanceUsd, isLoading }: BalanceDisplayProps = $props();

const balanceDkk = $derived(balanceUsd !== null ? usdToDkk(balanceUsd) : null);
</script>

<Tooltip>
  <!--
    The Kobalte source rendered this trigger as a div via its polymorphic `as` prop.
    bits-ui has no such prop, so the element is supplied through the `child` snippet;
    the spread carries the ARIA wiring and event handlers that open the tooltip.
    Rendering the default button element instead would change the DOM and the a11y tree.
  -->
  <TooltipTrigger>
    {#snippet child({ props })}
      <div {...props} class="text-muted-foreground flex cursor-help items-center gap-1.5 text-sm">
        <span class="i-carbon-wallet"></span>
        {#if !isLoading && balanceUsd !== null}
          <span>{formatDkk(balanceDkk!)}</span>
        {:else}
          {#if isLoading}
            <span class="animate-pulse">...</span>
          {:else}
            <span class="text-destructive">--</span>
          {/if}
        {/if}
      </div>
    {/snippet}
  </TooltipTrigger>
  <TooltipContent class="max-w-xs">{t("balance.tooltip")}</TooltipContent>
</Tooltip>

// src/components/BalanceDisplay.tsx
import { Show, type Component } from "solid-js";
import { formatDkk, usdToDkk } from "@config/pricing";
import { Tooltip, TooltipTrigger, TooltipContent } from "@components/ui/tooltip";
import { t } from "@lib/i18n";

interface BalanceDisplayProps {
  /** Balance in USD (null when loading/error) */
  balanceUsd: number | null;
  /** Whether balance is currently being fetched */
  isLoading: boolean;
}

export const BalanceDisplay: Component<BalanceDisplayProps> = (props) => {
  const balanceDkk = () =>
    props.balanceUsd !== null ? usdToDkk(props.balanceUsd) : null;

  return (
    <Tooltip>
      <TooltipTrigger
        as="div"
        class="flex items-center gap-1.5 text-sm text-muted-foreground cursor-help"
      >
        <span class="i-carbon-wallet" />
        <Show
          when={!props.isLoading && props.balanceUsd !== null}
          fallback={
            <Show
              when={props.isLoading}
              fallback={<span class="text-destructive">--</span>}
            >
              <span class="animate-pulse">...</span>
            </Show>
          }
        >
          <span>{formatDkk(balanceDkk()!)}</span>
        </Show>
      </TooltipTrigger>
      <TooltipContent class="max-w-xs">
        {t("balance.tooltip")}
      </TooltipContent>
    </Tooltip>
  );
};
