// src/components/onboarding/StepIndicator.svelte
<script lang="ts">
  interface Props {
    totalSteps: number;
    currentStep: number;
  }

  let { totalSteps, currentStep }: Props = $props();
</script>

<div class="mb-6 flex items-center justify-center gap-2">
  {#each Array(totalSteps) as _, index (index)}
    <div
      class={`h-2 rounded-full transition-all duration-300 ${
        index < currentStep
          ? "bg-primary w-2"
          : index === currentStep
            ? "bg-primary w-6"
            : "bg-muted w-2"
      }`}
    ></div>
  {/each}
</div>

// src/components/onboarding/StepIndicator.tsx
import type { Component } from "solid-js";
import { For } from "solid-js";

interface StepIndicatorProps {
  totalSteps: number;
  currentStep: number;
}

export const StepIndicator: Component<StepIndicatorProps> = (props) => {
  return (
    <div class="flex items-center justify-center gap-2 mb-6">
      <For each={Array.from({ length: props.totalSteps })}>
        {(_, index) => (
          <div
            class={`h-2 rounded-full transition-all duration-300 ${
              index() < props.currentStep
                ? "w-2 bg-primary"
                : index() === props.currentStep
                  ? "w-6 bg-primary"
                  : "w-2 bg-muted"
            }`}
          />
        )}
      </For>
    </div>
  );
};
